//! Shared proptest strategies and IDL model types for property-based tests.
//!
//! This module provides:
//!
//! - **Strategy functions** that generate `solana_parser::solana::structs::IdlType`
//!   values directly, with no mirror enum types:
//!   - [`arb_primitive_idl_type`] — any primitive `IdlType` variant
//!   - [`arb_idl_type`] — primitive or single-level container `IdlType`
//!   - [`idl_type_to_json`] — convert an `IdlType` to its Anchor JSON wire form
//!
//! - **Composite model structs** with `#[derive(Arbitrary)]` whose `IdlType`
//!   fields are generated via the strategy functions above:
//!   - [`ArbIdl`] — a random IDL with 1–16 instructions
//!   - [`ArbDefinedStructIdl`] — an IDL that references a defined struct type
//!   - [`ArbVecArgIdl`] — an IDL with a single `Vec<T>` instruction arg
//!
//! The exhaustive `match` in [`idl_type_to_json`] and in `arb_bytes_for_type`
//! (in `fuzz_idl_parsing.rs`) ensures a compile error if `IdlType` ever gains
//! or loses a variant in `solana_parser`.

#![allow(dead_code)]

use proptest::prelude::*;
use proptest_derive::Arbitrary;
use solana_parser::solana::structs::IdlType;

// ── Strategy functions ────────────────────────────────────────────────────────

/// Strategy that generates any primitive `IdlType` (no container wrappers).
pub fn arb_primitive_idl_type() -> BoxedStrategy<IdlType> {
    prop_oneof![
        Just(IdlType::Bool),
        Just(IdlType::U8),
        Just(IdlType::U16),
        Just(IdlType::U32),
        Just(IdlType::U64),
        Just(IdlType::U128),
        Just(IdlType::I8),
        Just(IdlType::I16),
        Just(IdlType::I32),
        Just(IdlType::I64),
        Just(IdlType::I128),
        Just(IdlType::F32),
        Just(IdlType::F64),
        Just(IdlType::PublicKey),
        Just(IdlType::String),
        Just(IdlType::Bytes),
    ]
    .boxed()
}

/// Strategy that generates a primitive or single-level container `IdlType`.
///
/// Weights: 4 primitive : 1 Vec : 1 Option : 1 Array : 1 VecOption :
///          1 OptionVec — matching the original manual `arb_idl_type()`.
pub fn arb_idl_type() -> BoxedStrategy<IdlType> {
    prop_oneof![
        4 => arb_primitive_idl_type(),
        1 => arb_primitive_idl_type().prop_map(|p| IdlType::Vec(Box::new(p))),
        1 => arb_primitive_idl_type().prop_map(|p| IdlType::Option(Box::new(p))),
        1 => arb_primitive_idl_type().prop_flat_map(|p| {
            (1usize..=4usize).prop_map(move |n| IdlType::Array(Box::new(p.clone()), n))
        }),
        1 => arb_primitive_idl_type()
            .prop_map(|p| IdlType::Vec(Box::new(IdlType::Option(Box::new(p))))),
        1 => arb_primitive_idl_type()
            .prop_map(|p| IdlType::Option(Box::new(IdlType::Vec(Box::new(p))))),
    ]
    .boxed()
}

/// Convert an `IdlType` to its Anchor IDL JSON wire representation.
///
/// The exhaustive `match` here is the compile-time safety anchor: any new
/// variant added to `IdlType` in `solana_parser` will produce a compile error.
///
/// # Note on `Defined`
///
/// The strategy functions [`arb_primitive_idl_type`] and [`arb_idl_type`] do
/// not generate `IdlType::Defined` variants — those are exercised separately
/// via [`ArbDefinedStructIdl`], which controls both the struct definition in the
/// `types` array and the reference in the instruction arg.  This function still
/// handles `Defined` so that `ArbDefinedStructIdl::to_json_string` can call it
/// on an `ArbIdlArg::ty` that was generated by `arb_idl_type()` (which may
/// appear alongside the defined-type arg in the extra instructions).
pub fn idl_type_to_json(ty: &IdlType) -> serde_json::Value {
    match ty {
        IdlType::Bool => serde_json::json!("bool"),
        IdlType::U8 => serde_json::json!("u8"),
        IdlType::U16 => serde_json::json!("u16"),
        IdlType::U32 => serde_json::json!("u32"),
        IdlType::U64 => serde_json::json!("u64"),
        IdlType::U128 => serde_json::json!("u128"),
        IdlType::I8 => serde_json::json!("i8"),
        IdlType::I16 => serde_json::json!("i16"),
        IdlType::I32 => serde_json::json!("i32"),
        IdlType::I64 => serde_json::json!("i64"),
        IdlType::I128 => serde_json::json!("i128"),
        IdlType::F32 => serde_json::json!("f32"),
        IdlType::F64 => serde_json::json!("f64"),
        IdlType::PublicKey => serde_json::json!("publicKey"),
        IdlType::String => serde_json::json!("string"),
        IdlType::Bytes => serde_json::json!("bytes"),
        IdlType::Vec(inner) => serde_json::json!({ "vec": idl_type_to_json(inner) }),
        IdlType::Option(inner) => serde_json::json!({ "option": idl_type_to_json(inner) }),
        IdlType::Array(inner, n) => serde_json::json!({ "array": [idl_type_to_json(inner), n] }),
        IdlType::Defined(d) => serde_json::json!({ "defined": d.to_string() }),
    }
}

// ── Instruction model ─────────────────────────────────────────────────────────

/// A single instruction argument: a name and an IDL type.
#[derive(Debug, Clone, Arbitrary)]
pub struct ArbIdlArg {
    #[proptest(regex = "[a-z][a-z0-9]{1,15}")]
    pub name: String,
    #[proptest(strategy = "arb_idl_type()")]
    pub ty: IdlType,
}

impl ArbIdlArg {
    pub fn to_json(&self) -> serde_json::Value {
        serde_json::json!({ "name": self.name, "type": idl_type_to_json(&self.ty) })
    }
}

/// A single IDL instruction: a name and 0–20 arguments.
#[derive(Debug, Clone, Arbitrary)]
pub struct ArbIdlInstruction {
    #[proptest(regex = "[a-z][a-z0-9]{1,15}")]
    pub name: String,
    #[proptest(strategy = "prop::collection::vec(any::<ArbIdlArg>(), 0..=20)")]
    pub args: Vec<ArbIdlArg>,
}

impl ArbIdlInstruction {
    pub fn to_json(&self) -> serde_json::Value {
        let args: Vec<_> = self.args.iter().map(ArbIdlArg::to_json).collect();
        serde_json::json!({ "name": self.name, "accounts": [], "args": args })
    }
}

// ── Top-level IDL ─────────────────────────────────────────────────────────────

/// A full IDL with 1–16 randomly-structured instructions and no defined types.
#[derive(Debug, Arbitrary)]
pub struct ArbIdl {
    #[proptest(strategy = "prop::collection::vec(any::<ArbIdlInstruction>(), 1..=16)")]
    pub instructions: Vec<ArbIdlInstruction>,
}

impl ArbIdl {
    pub fn to_json_string(&self) -> String {
        let insts: Vec<_> = self
            .instructions
            .iter()
            .map(ArbIdlInstruction::to_json)
            .collect();
        serde_json::json!({ "instructions": insts, "types": [] }).to_string()
    }
}

// ── Defined-struct IDL ────────────────────────────────────────────────────────

/// A struct field with a primitive type (no nested defined types, to avoid
/// unbounded recursion in `arb_bytes_for_type`).
#[derive(Debug, Clone, Arbitrary)]
pub struct ArbStructField {
    #[proptest(regex = "[a-z][a-z0-9]{1,15}")]
    pub name: String,
    #[proptest(strategy = "arb_primitive_idl_type()")]
    pub ty: IdlType,
}

/// An IDL where one instruction references a defined struct from the `types`
/// array.  Used to exercise the `Defined` type-resolution path.
#[derive(Debug, Arbitrary)]
pub struct ArbDefinedStructIdl {
    #[proptest(regex = "[a-z][a-z0-9]{1,15}")]
    pub struct_name: String,
    #[proptest(strategy = "prop::collection::vec(any::<ArbStructField>(), 1..=8)")]
    pub fields: Vec<ArbStructField>,
    #[proptest(regex = "[a-z][a-z0-9]{1,15}")]
    pub inst_name: String,
    /// Extra instructions using primitive args (not the defined type).
    #[proptest(strategy = "prop::collection::vec(any::<ArbIdlInstruction>(), 0..=4)")]
    pub extra_insts: Vec<ArbIdlInstruction>,
}

impl ArbDefinedStructIdl {
    pub fn to_json_string(&self) -> String {
        let field_jsons: Vec<_> = self
            .fields
            .iter()
            .map(|f| serde_json::json!({ "name": f.name, "type": idl_type_to_json(&f.ty) }))
            .collect();
        let main_inst = serde_json::json!({
            "name": self.inst_name,
            "accounts": [],
            "args": [{ "name": "data", "type": { "defined": self.struct_name } }]
        });
        let mut all_insts: Vec<_> = self
            .extra_insts
            .iter()
            .map(ArbIdlInstruction::to_json)
            .collect();
        all_insts.push(main_inst);
        serde_json::json!({
            "instructions": all_insts,
            "types": [{
                "name": self.struct_name,
                "type": { "kind": "struct", "fields": field_jsons }
            }]
        })
        .to_string()
    }
}

// ── Vec-arg IDL ───────────────────────────────────────────────────────────────

/// An IDL with exactly one instruction that has a single `Vec<T>` argument.
/// Used to stress-test the SizeGuard against large length-prefix claims.
#[derive(Debug, Arbitrary)]
pub struct ArbVecArgIdl {
    #[proptest(regex = "[a-z][a-z0-9]{1,15}")]
    pub inst_name: String,
    #[proptest(strategy = "arb_idl_type()")]
    pub elem_type: IdlType,
}

impl ArbVecArgIdl {
    pub fn to_json_string(&self) -> String {
        serde_json::json!({
            "instructions": [{
                "name": self.inst_name,
                "accounts": [],
                "args": [{ "name": "data", "type": { "vec": idl_type_to_json(&self.elem_type) } }]
            }],
            "types": []
        })
        .to_string()
    }
}
