// Module declarations are auto-generated by `build.rs`. The generated
// file emits one `pub mod <name>;` per direct subdirectory of
// `src/presets/` that contains a `mod.rs`. Drop in a new preset and
// it's wired up on the next build -- no manual edit here.
include!(concat!(env!("OUT_DIR"), "/presets_mod.rs"));
