#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
//! IDL discriminator fuzz, plus a small surfpool-backed check that the fork
//! those tests start (in the lifecycle test below) actually serves real
//! mainnet state.
//!
//! Most tests here (`idl_tests!` pairs, `surfpool_preset_idls`,
//! `surfpool_idl_from_env`) are purely local: they decode an IDL, build a
//! synthetic transaction from its first instruction's discriminator, and run
//! it through the converter. No network access, no `surfpool` binary, not
//! `#[ignore]` -- they run on every plain `cargo test -p visualsign-solana`.
//!
//! `surfpool_lifecycle` and `surfpool_program_executable` are the only tests
//! that start a `surfpool` mainnet fork and require the `surfpool` binary on
//! `$PATH`; both are `#[ignore]`. `surfpool_program_executable` is what
//! actually asserts against fork-served state -- it fetches a well-known
//! executable program account and checks its `executable`/`owner` fields, so
//! a bad datasource (or a dead-fork regression) fails a real assertion,
//! not "not-`--ignored`" text-only proof.
//!
//! Run the surfpool-backed tests:
//!
//! ```bash
//! HELIUS_API_KEY=<key> cargo test \
//!     --manifest-path src/Cargo.toml -p visualsign-solana \
//!     --test surfpool_fuzz -- --ignored
//! ```
//!
//! Run a single IDL fuzz test (no `--ignored`, no fork):
//!
//! ```bash
//! cargo test --manifest-path src/Cargo.toml -p visualsign-solana \
//!     --test surfpool_fuzz surfpool_idl_jupiter
//! ```
//!
//! Adding a new IDL:
//! - Upstream `solana_parser::solana::embedded_idls::*`: add a `use` import and
//!   a `name => CONST` pair to the `idl_tests! { ... }` block below.
//!   `idl_tests_cover_all_program_types` fails a plain `cargo test` run if
//!   the resulting `NAMED_IDLS` list drifts from
//!   `solana_parser::ProgramType::all()`.
//! - Vsp-local preset IDL (e.g. one added by the `solana-add-idl` skill):
//!   drop a `.json` file anywhere directly under `src/presets/<name>/`.
//!   `build.rs` discovers it and `surfpool_preset_idls` (below) iterates it
//!   on every run -- no test-file edit required.
//!
//! To fuzz a candidate IDL before it's embedded upstream, set `IDL_FILE` to
//! its path and run `surfpool_idl_from_env` (see below).

mod common;

use std::collections::BTreeSet;

use common::load_idl_from_env;
use solana_parser::solana::embedded_idls::{
    APE_PRO_IDL, CANDY_MACHINE_IDL, DRIFT_IDL, JUPITER_AGG_V6_IDL, JUPITER_IDL, JUPITER_LIMIT_IDL,
    KAMINO_IDL, LIFINITY_IDL, METEORA_IDL, OPENBOOK_IDL, ORCA_IDL, RAYDIUM_IDL, STABBLE_IDL,
};
use solana_sdk::pubkey::Pubkey;
use solana_test_utils::{SurfpoolConfig, SurfpoolManager};

/// Smoke test: start surfpool, verify the RPC responds, let `Drop` tear it down.
#[tokio::test(flavor = "multi_thread")]
#[ignore]
async fn surfpool_lifecycle() {
    let manager = SurfpoolManager::start(SurfpoolConfig::default())
        .await
        .expect("surfpool should start");

    let client = manager.rpc_client();
    let version = client
        .get_version()
        .expect("RPC should respond with a version");

    assert!(
        !version.solana_core.is_empty(),
        "solana_core version string must not be empty"
    );
}

// `collision.json` and `cyclic.json` exist in `solana_parser`'s `idls/`
// directory but are negative test fixtures (duplicate type names / cyclic
// type refs); they're rejected by `decode_idl_data` and therefore not
// exposed via `embedded_idls`.

idl_tests! {
    surfpool_idl_ape_pro => APE_PRO_IDL,
    surfpool_idl_candy_machine => CANDY_MACHINE_IDL,
    surfpool_idl_drift => DRIFT_IDL,
    surfpool_idl_jupiter => JUPITER_IDL,
    surfpool_idl_jupiter_agg_v6 => JUPITER_AGG_V6_IDL,
    surfpool_idl_jupiter_limit => JUPITER_LIMIT_IDL,
    surfpool_idl_kamino => KAMINO_IDL,
    surfpool_idl_lifinity => LIFINITY_IDL,
    surfpool_idl_meteora => METEORA_IDL,
    surfpool_idl_openbook => OPENBOOK_IDL,
    surfpool_idl_orca => ORCA_IDL,
    surfpool_idl_raydium => RAYDIUM_IDL,
    surfpool_idl_stabble => STABBLE_IDL,
}

/// Guards against `NAMED_IDLS` (generated by the `idl_tests!` block above,
/// alongside the tests themselves) drifting from `solana_parser::ProgramType::all()`
/// -- the enumerable list of every built-in program type upstream, whose
/// `idl_json()` returns exactly the `embedded_idls` consts used above. If a
/// future rev bump adds or removes a variant without a matching pair above,
/// this fails and names the gap, instead of silently leaving the new IDL
/// untested. Because `NAMED_IDLS` is generated by the same macro invocation
/// that creates the tests, deleting a pair above can't leave a stale, still-
/// "covered" entry behind the way a hand-maintained list could.
///
/// Not `#[ignore]`: this is a pure data comparison, no surfpool fork needed,
/// so it runs on every plain `cargo test -p visualsign-solana`.
#[test]
fn idl_tests_cover_all_program_types() {
    let named: BTreeSet<&str> = NAMED_IDLS.iter().copied().collect();

    let upstream: BTreeSet<&str> = solana_parser::ProgramType::all()
        .iter()
        .map(solana_parser::ProgramType::idl_json)
        .collect();

    assert_eq!(
        named, upstream,
        "the idl_tests!{{}} pairs in this file no longer match \
         solana_parser::ProgramType::all() -- add or remove a pair above for \
         the program type(s) that changed"
    );
}

/// Fuzz a candidate IDL before it's embedded upstream in
/// `solana_parser::embedded_idls`. Skips gracefully when `IDL_FILE` is unset --
/// this is a manual pre-merge check, not part of the standard suite run by CI.
///
/// Purely local, like `idl_discriminator_roundtrip` -- no fork involved.
#[test]
fn surfpool_idl_from_env() {
    let Some((idl_json, _idl)) = load_idl_from_env() else {
        eprintln!("IDL_FILE not set or invalid -- skipping surfpool_idl_from_env");
        return;
    };
    common::idl_discriminator_roundtrip("surfpool_idl_from_env", &idl_json);
}

/// Auto-discovered preset IDLs: every `.json` file `build.rs` finds directly
/// under a `src/presets/<name>/` directory is fuzzed here through the same
/// discriminator roundtrip used by the named `idl_tests!` pairs above. The
/// skill (and any future contributor) only needs to drop the JSON file --
/// this test picks it up without any code edit, regardless of filename. Empty
/// when no presets ship an IDL JSON.
///
/// Purely local, like `idl_discriminator_roundtrip` -- no fork involved.
#[test]
fn surfpool_preset_idls() {
    for (name, idl_json) in visualsign_solana::PRESET_IDLS {
        common::idl_discriminator_roundtrip(&format!("preset_{name}"), idl_json);
    }
}

/// Jupiter Aggregator V6 -- a real, executable mainnet program used to prove
/// the fork in [`surfpool_program_executable`] serves live on-chain state.
const JUPITER_AGG_V6_PROGRAM_ID: &str = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4";

/// The BPF Loader Upgradeable program, which owns
/// [`JUPITER_AGG_V6_PROGRAM_ID`]'s executable account on mainnet.
const BPF_LOADER_UPGRADEABLE_PROGRAM_ID: &str = "BPFLoaderUpgradeab1e11111111111111111111111";

/// The one test in this file whose assertion actually depends on the
/// `surfpool` fork: fetches a well-known executable program account through
/// it and checks `executable`/`owner`. Every `idl_tests!` pair above, plus
/// `surfpool_preset_idls` and `surfpool_idl_from_env`, is a local
/// discriminator fuzz that needs no fork at all -- this is the test that
/// would fail if the fork stopped serving real mainnet state.
#[tokio::test(flavor = "multi_thread")]
#[ignore]
async fn surfpool_program_executable() {
    let manager = SurfpoolManager::start(SurfpoolConfig::default())
        .await
        .expect("surfpool should start");

    let program_id: Pubkey = JUPITER_AGG_V6_PROGRAM_ID
        .parse()
        .expect("hardcoded pubkey literal should parse");
    let account = manager
        .get_account(&program_id)
        .await
        .expect("get_account should succeed")
        .expect("Jupiter Aggregator V6 should exist on the mainnet fork");

    assert!(account.executable, "program account must be executable");
    assert_eq!(
        account.owner.to_string(),
        BPF_LOADER_UPGRADEABLE_PROGRAM_ID,
        "program account should be owned by the BPF Loader Upgradeable program"
    );
}
