FROM stagex/pallet-rust:1.88.0@sha256:b9021d2b75eac64fe8b931d96dde63ef11792e5023cee77c3471ccc34a95a377 AS build

# Rust configuration
ENV RUSTFLAGS='-C target-feature=+crt-static'
ENV CARGOFLAGS='--target x86_64-unknown-linux-musl --no-default-features --locked --release'

# Directory for Rust artifacts
ENV RELEASE_DIR=/src/target/x86_64-unknown-linux-musl/release

# Load Rust sources
ADD src /src
WORKDIR /src/

# pre-fetch all workspace deps; we need them to build with `--network=none` later
RUN cargo fetch

WORKDIR /src/parser/cli
RUN --network=none <<-EOF
    set -eu
    cargo build ${CARGOFLAGS} --features solana
    mkdir -p /rootfs/usr/local/bin
    mv ${RELEASE_DIR}/parser_cli /rootfs/usr/local/bin/
EOF

FROM scratch AS package
COPY --from=build /rootfs/. .
