//! DApp integrations. Module declarations are auto-generated by `build.rs`
//! from the `src/integrations/` directory listing, which keeps this file
//! conflict-free across PRs that add new integrations.
//!
//! To add an integration: create `src/integrations/<name>/{mod.rs,config.rs,...}`.
//! Do NOT edit this file — it has no hand-maintained content.

include!(concat!(env!("OUT_DIR"), "/generated_integrations_mod.rs"));
