//! Preset visualizers. Module declarations are auto-generated by `build.rs`
//! from the `src/presets/` directory listing, which keeps this file
//! conflict-free across PRs that add new presets.
//!
//! To add a preset: create `src/presets/<name>/{mod.rs,config.rs,...}`. Do
//! NOT edit this file — it has no hand-maintained content.

include!(concat!(env!("OUT_DIR"), "/generated_presets_mod.rs"));
