// Build scripts run at compile time — panicking on failure is acceptable.
#![allow(clippy::unwrap_used)]

use std::{env, fs, path::PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/presets");
    println!("cargo:rerun-if-changed=src/integrations");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let visualizers = collect_visualizers();

    // We operate on instructions at a transaction level even though Solana uses programs and that's what we want to create the modules around
    // but each instruction may individually be special and has to be handled properly. This should allow use to functionally compose instructions
    // at the time of display too
    let code = format!(
        "pub fn available_visualizers() -> Vec<Box<dyn InstructionVisualizer>> {{
            vec![
                {}
            ]
        }}",
        visualizers.join(",\n")
    );

    fs::write(out_dir.join("generated_visualizers.rs"), code).unwrap();

    let preset_idls = collect_preset_idls();
    let preset_idls_code = format!(
        "/// Preset IDLs auto-discovered from `src/presets/<name>/<name>.json`.\n\
         ///\n\
         /// Generated by `build.rs`. Drop a JSON file at the matching path and\n\
         /// it appears here on the next build -- no manual registration. Used\n\
         /// by the surfpool roundtrip test to exercise every embedded IDL.\n\
         pub const PRESET_IDLS: &[(&str, &str)] = &[\n    {}\n];\n",
        preset_idls.join(",\n    ")
    );
    fs::write(out_dir.join("preset_idls.rs"), preset_idls_code).unwrap();

    let preset_mods = collect_preset_mods();
    let preset_mods_code = format!(
        "// Auto-generated by `build.rs`. One `pub mod` per directory under\n\
         // `src/presets/` that contains a `mod.rs`. Drop in a new preset\n\
         // directory and it shows up here on the next build -- no manual\n\
         // edit of `presets/mod.rs` required.\n\
         {}\n",
        preset_mods.join("\n")
    );
    fs::write(out_dir.join("presets_mod.rs"), preset_mods_code).unwrap();
}

fn collect_visualizers() -> Vec<String> {
    let all_visualizers: Vec<(String, String)> = [
        ("src/presets", "crate::presets"),
        ("src/integrations", "crate::integrations"),
    ]
    .iter()
    .flat_map(|(folder_name, module_root)| {
        fs::read_dir(folder_name)
            .unwrap()
            .filter_map(|entry| {
                let entry = entry.ok()?;
                let path = entry.path();

                if path.is_dir() {
                    let dir_name = path.file_name()?.to_str()?.to_string();
                    let visualizer_string = format!(
                        "Box::new({}::{}::{}Visualizer)",
                        module_root,
                        dir_name,
                        to_pascal_case(&dir_name)
                    );
                    Some((dir_name, visualizer_string))
                } else {
                    None
                }
            })
            .collect::<Vec<_>>()
    })
    .collect();

    // Partition: specific visualizers first, unknown_program visualizer last (it's a catch-all)
    let (unknown, specific): (Vec<_>, Vec<_>) = all_visualizers
        .into_iter()
        .partition(|(name, _)| name == "unknown_program");

    specific
        .into_iter()
        .map(|(_, vis)| vis)
        .chain(unknown.into_iter().map(|(_, vis)| vis))
        .collect()
}

fn collect_preset_mods() -> Vec<String> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let presets_dir = PathBuf::from(&manifest_dir).join("src/presets");
    let Ok(entries) = fs::read_dir(&presets_dir) else {
        return Vec::new();
    };
    let mut mods: Vec<String> = entries
        .filter_map(|entry| {
            let path = entry.ok()?.path();
            if !path.is_dir() {
                return None;
            }
            // Only emit `pub mod` for directories that actually contain a
            // mod.rs. An empty subdirectory would otherwise produce a
            // confusing compile error pointing at generated code.
            let mod_rs = path.join("mod.rs");
            if !mod_rs.exists() {
                return None;
            }
            let dir_name = path.file_name()?.to_str()?.to_string();
            // The generated file lives in OUT_DIR; `mod` resolution is
            // relative to *its* location, so without `#[path]` rustc looks
            // for `OUT_DIR/<name>.rs`. The absolute path attribute pins
            // resolution to the real source tree.
            Some(format!(
                "#[path = \"{path}\"]\npub mod {dir_name};",
                path = mod_rs.display()
            ))
        })
        .collect();
    mods.sort();
    mods
}

fn collect_preset_idls() -> Vec<String> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let presets_dir = PathBuf::from(&manifest_dir).join("src/presets");
    let Ok(entries) = fs::read_dir(&presets_dir) else {
        return Vec::new();
    };
    let mut idls: Vec<String> = entries
        .filter_map(|entry| {
            let path = entry.ok()?.path();
            if !path.is_dir() {
                return None;
            }
            let dir_name = path.file_name()?.to_str()?.to_string();
            let json_path = path.join(format!("{dir_name}.json"));
            if !json_path.exists() {
                return None;
            }
            // include_str! takes a literal; emit the absolute path as-is. The
            // `cargo:rerun-if-changed=src/presets` directive triggers a rebuild
            // when the JSON file is added, removed, or modified.
            Some(format!(
                "(\"{name}\", include_str!(\"{path}\"))",
                name = dir_name,
                path = json_path.display()
            ))
        })
        .collect();
    idls.sort();
    idls
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("system"), "System");
        assert_eq!(to_pascal_case("unknown_program"), "UnknownProgram");
        assert_eq!(to_pascal_case("jupiter_swap"), "JupiterSwap");
        assert_eq!(
            to_pascal_case("associated_token_account"),
            "AssociatedTokenAccount"
        );
    }

    #[test]
    fn test_collect_visualizers_unknown_program_last() {
        let visualizers = collect_visualizers();

        // unknown_program should be last since it's a catch-all
        if let Some(last) = visualizers.last() {
            assert!(
                last.contains("unknown_program") || last.contains("UnknownProgram"),
                "Unknown program visualizer should be last, but got: {}",
                last
            );
        }
    }

    #[test]
    fn test_collect_visualizers_not_empty() {
        let visualizers = collect_visualizers();
        assert!(
            !visualizers.is_empty(),
            "Should have at least one visualizer"
        );
    }

    #[test]
    fn test_collect_preset_mods_emits_path_attribute_per_preset() {
        // Every preset directory with a mod.rs should produce one
        // `#[path = ...] pub mod <name>;` line. Without the path
        // attribute, `include!`'d `pub mod` would resolve relative to
        // OUT_DIR and break the build.
        let mods = collect_preset_mods();
        assert!(!mods.is_empty(), "Should discover at least one preset");
        for line in &mods {
            assert!(
                line.starts_with("#[path = \""),
                "Each entry must pin the source path: {line}"
            );
            assert!(
                line.contains("pub mod "),
                "Each entry must declare a module: {line}"
            );
        }
        // Sorted so diffs stay stable as presets are added.
        let mut sorted = mods.clone();
        sorted.sort();
        assert_eq!(mods, sorted, "collect_preset_mods output must be sorted");
    }

    #[test]
    fn test_collect_preset_mods_skips_dirs_without_mod_rs() {
        // The current preset tree has a mod.rs in every directory.
        // If any future scaffolding leaves a JSON-only directory behind,
        // this guard prevents it from producing a confusing build break.
        let mods = collect_preset_mods();
        for line in &mods {
            // Extract the path between #[path = "..."]
            let start = line.find('"').unwrap() + 1;
            let end = line[start..].find('"').unwrap() + start;
            let path = &line[start..end];
            assert!(
                std::path::Path::new(path).exists(),
                "Generated #[path] points at a non-existent file: {path}"
            );
        }
    }

    #[test]
    fn test_collect_preset_idls_returns_only_dirs_with_matching_json() {
        // Currently no preset ships an embedded IDL JSON, so the slice
        // is expected to be empty. When the first preset adds one, this
        // test will need updating -- which is the point: it locks in
        // the discovery contract.
        let idls = collect_preset_idls();
        for entry in &idls {
            assert!(
                entry.starts_with('('),
                "Entries must be tuple-shaped: {entry}"
            );
            assert!(
                entry.contains("include_str!"),
                "Entries must embed JSON: {entry}"
            );
        }
        let mut sorted = idls.clone();
        sorted.sort();
        assert_eq!(idls, sorted, "collect_preset_idls output must be sorted");
    }
}
