name: stagex (visualsign-solana)

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "main"
    paths:
      - ".github/**"
      - "Makefile"
      - "images/visualsign-solana/**"
      - "src/Cargo.toml"
      - "src/Cargo.lock"
      - "src/bin/visualsign-solana/**"
      - "src/chain_parsers/visualsign-solana/**"
      - "src/chain_parsers/visualsign-unspecified/**"
      - "src/visualsign/**"
      - "src/generated/**"
      - "src/parser/cli/**"
  pull_request:
    paths:
      - ".github/**"
      - "Makefile"
      - "images/visualsign-solana/**"
      - "src/Cargo.toml"
      - "src/Cargo.lock"
      - "src/bin/visualsign-solana/**"
      - "src/chain_parsers/visualsign-solana/**"
      - "src/chain_parsers/visualsign-unspecified/**"
      - "src/visualsign/**"
      - "src/generated/**"
      - "src/parser/cli/**"
  workflow_dispatch: # Allows manual invocation

jobs:
  build:
    name: Build parser images (visualsign-solana)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
      packages: write
    env:
      tags: >-
        ${{ github.ref == format('refs/heads/{0}', 'main') && 'latest' || '' }}
        ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || '' }}
        ${{ github.event_name == 'push' && github.ref_name || '' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker setup
        uses: ./.github/actions/docker-setup
        with:
          dockerHub: ${{ secrets.DOCKERHUB_API_KEY }}
          ghcr: ${{ secrets.GITHUB_TOKEN }}

      - name: Build visualsign-solana
        shell: bash
        run: |
          make -j$(nproc) out/visualsign-solana/index.json

      - name: Load artifact to Docker
        run: |
          env -C out/visualsign-solana tar -cf - . | docker load

      - name: Upload to GHCR
        run: |
          for tag in ${tags}; do
              docker tag "anchorageoss-visualsign-parser/visualsign-solana:latest" "ghcr.io/anchorageoss/visualsign-solana:${tag}"
          done
          docker image push --all-tags "ghcr.io/anchorageoss/visualsign-solana"
